shallow_clone: true

platform:
  - x86
  - x64

environment:
  matrix:
  - { LUA: "lua 5.1",    TARGET: mingw }
  - { LUA: "lua 5.1",    TARGET: vs }
  - { LUA: "lua 5.2",    TARGET: mingw }
  - { LUA: "lua 5.2",    TARGET: vs }
  - { LUA: "lua 5.3",    TARGET: mingw }
  - { LUA: "lua 5.3",    TARGET: vs }
  - { LUA: "luajit 2.0", TARGET: mingw }
  - { LUA: "luajit 2.0", TARGET: vs }
  - { LUA: "luajit 2.1", TARGET: mingw }
  - { LUA: "luajit 2.1", TARGET: vs }

init:
  # openssl headers + library
  ## Set before calling vcvarsall, as it changes platform
  - if %platform%==x86 set OPENSSL_DIR=C:\OpenSSL-Win32
  - if %platform%==x64 set OPENSSL_DIR=C:\OpenSSL-Win64
  # set mingw paths
  - if %platform%==x86 set MINGW_PATH=C:\mingw-w64\i686-6.3.0-posix-dwarf-rt_v5-rev1\mingw32\bin
  - if %platform%==x64 set MINGW_PATH=C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1\mingw64\bin
  - if %TARGET%==mingw set PATH=%MINGW_PATH%;%PATH%
  # luarocks on mingw defaults to using mingw32-gcc as CC and LD
  - if %TARGET%==mingw set LUAROCKS_FLAGS=CC=gcc LD=gcc
  # set MSVC paths
  - if %TARGET%==vs    call "%ProgramFiles(x86)%\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" %platform%

before_build:
  - set PATH=C:\Python27\Scripts;%PATH% # Add directory containing 'pip' to PATH
  - pip install hererocks
  - hererocks env --%LUA% -rlatest --target=%TARGET%
  - call env\bin\activate

build_script:
  - copy config.h.guess src\config.h
  - luarocks make luaossl-scm-0.rockspec OPENSSL_DIR=%OPENSSL_DIR% CRYPTO_DIR=%OPENSSL_DIR% %LUAROCKS_FLAGS%
  - luarocks pack luaossl

test_script:
  - lua -e "require'openssl.digest'"

artifacts:
  - path: luaossl-*.rock
